/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PenugasanRouteImport } from './routes/penugasan'
import { Route as ManajemenRouteImport } from './routes/manajemen'
import { Route as EvaluasiRouteImport } from './routes/evaluasi'
import { Route as AnalitikRouteImport } from './routes/analitik'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PenugasanRoute = PenugasanRouteImport.update({
  id: '/penugasan',
  path: '/penugasan',
  getParentRoute: () => rootRouteImport,
} as any)
const ManajemenRoute = ManajemenRouteImport.update({
  id: '/manajemen',
  path: '/manajemen',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluasiRoute = EvaluasiRouteImport.update({
  id: '/evaluasi',
  path: '/evaluasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalitikRoute = AnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/evaluasi': typeof EvaluasiRoute
  '/manajemen': typeof ManajemenRoute
  '/penugasan': typeof PenugasanRoute
  '/profil': typeof ProfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/evaluasi': typeof EvaluasiRoute
  '/manajemen': typeof ManajemenRoute
  '/penugasan': typeof PenugasanRoute
  '/profil': typeof ProfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/evaluasi': typeof EvaluasiRoute
  '/manajemen': typeof ManajemenRoute
  '/penugasan': typeof PenugasanRoute
  '/profil': typeof ProfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analitik'
    | '/evaluasi'
    | '/manajemen'
    | '/penugasan'
    | '/profil'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analitik'
    | '/evaluasi'
    | '/manajemen'
    | '/penugasan'
    | '/profil'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/analitik'
    | '/evaluasi'
    | '/manajemen'
    | '/penugasan'
    | '/profil'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalitikRoute: typeof AnalitikRoute
  EvaluasiRoute: typeof EvaluasiRoute
  ManajemenRoute: typeof ManajemenRoute
  PenugasanRoute: typeof PenugasanRoute
  ProfilRoute: typeof ProfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penugasan': {
      id: '/penugasan'
      path: '/penugasan'
      fullPath: '/penugasan'
      preLoaderRoute: typeof PenugasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manajemen': {
      id: '/manajemen'
      path: '/manajemen'
      fullPath: '/manajemen'
      preLoaderRoute: typeof ManajemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluasi': {
      id: '/evaluasi'
      path: '/evaluasi'
      fullPath: '/evaluasi'
      preLoaderRoute: typeof EvaluasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitik': {
      id: '/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AnalitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalitikRoute: AnalitikRoute,
  EvaluasiRoute: EvaluasiRoute,
  ManajemenRoute: ManajemenRoute,
  PenugasanRoute: PenugasanRoute,
  ProfilRoute: ProfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
